### ISSUE TITLE
some errors... maybe requires C++17?

### ISSUE THREAD

**Issue by moebiussurfing** [kem0x/ImTween#1]
Hey @kem0x ,
thanks for sharing this.

Did you used c++17 or 20 maybe?

I am getting some errors here in C++14 
and I suspect that's the problem.

```
Error	C2143	syntax error: missing ';' before '<' 
 std::optional<std::function<void()>> onComplete;
```

PS: 
Do you have any screenshots/gifs to see how is looking the tween in other situations like menus and so?

**Comment by kem0x** [comment]
![image](https://user-images.githubusercontent.com/19430119/215563284-415c4a01-fc7c-4ef9-893c-010c47cdf84c.png)
`std::optional` was introduced with c++17, so yes my bad this header does require atleast c++17
